In [1]:
import os
os.chdir('/Users/aleksandrberezutskii/Desktop/GitHub/MPOpt/')
from mpopt.contractor.contractor import apply_one_site_unitary, apply_two_site_unitary, mps_mpo_contract
from mpopt.mps.explicit import *
from mpopt.utils.utils import *
from tests.mps.test_explicit import _create_psi
from experiments.ising import *
import numpy as np
import qecstruct as qec

In [2]:
NUM_BITS = 12
NUM_CHECKS = 9
BIT_DEGREE = 3
CHECK_DEGREE = 4
# TODO prob_noise -> prob_channel
PROB_NOISE = 0.2
PROB_ERROR = 0.1
if NUM_BITS / NUM_CHECKS != CHECK_DEGREE / BIT_DEGREE:
    raise ValueError("The graph must be bipartite.")

# Constructing the code as a qecstruct object, preparing the state.
example_code = qec.random_regular_code(
    NUM_BITS, NUM_CHECKS, BIT_DEGREE, CHECK_DEGREE, qec.Rng()
)

In [3]:
def linear_code_checks(code):
    """
    Given a linear code, returns a list of its checks, where each check
    is represented as a list of indices of the bits adjacent to it.
    Arguments:
        code : qecstruct.LinearCode
            Linear code object.
    Returns:
        checks : list of lists
            List of checks.
    """

    checks = []
    bits = range(code.length())
    parity_matrix = code.par_mat()

    for row in parity_matrix.rows():
        checks.append(np.flatnonzero([row.is_one_at(i) for i in bits]))

    return checks

In [4]:
example_code.has_codeword(qec.BinaryVector(12, [0,5,6,9]))

False

In [5]:
list(map(np.array, example_code.par_mat().rows()))

[array([0, 2, 5, 9], dtype=object),
 array([1, 2, 10, 11], dtype=object),
 array([6, 7, 9, 10], dtype=object),
 array([4, 5, 7, 11], dtype=object),
 array([3, 7, 8, 11], dtype=object),
 array([0, 6, 8, 10], dtype=object),
 array([0, 2, 4, 5], dtype=object),
 array([1, 3, 8, 9], dtype=object),
 array([1, 3, 4, 6], dtype=object)]

In [6]:
# TODO's
# check out the sanity tests they have in TenPy
# check out typing for fixing types of variables in functions
# dtypes: complex64/32? float64/32?
# bond dimensions check: mpss and mpos
# compress method for mps

In [14]:
a = np.zeros((2,3,4))
np.unravel_index(4, shape=a.shape)

(0, 1, 0)

In [7]:
from mpopt.utils.utils import kron_tensors
tensor_1 = np.random.uniform(size=(3, 13, 5))
tensor_2 = np.random.uniform(size=(7, 2, 11))